### ISSUE TITLE
My bad

### ISSUE THREAD

**Issue by pfrazee** [dat-ecosystem-archive/project-updates#1]
I accidentally added beaker and its project update directly to the repo. I thought I was pushing to my fork, so I could create a PR.

Should we correct that somehow or just roll with it?

**Comment by cblgh** [comment]
@pfrazee nah i think that's fine! 

the pull request mechanism exists to give people notifications that "oh hey paul published a new update!" it's just a kinda pragmatic thing that @RangerMauve come up with when we were jamming

**Comment by cblgh** [comment]
also: yay!
