### ISSUE TITLE
p2pcommons and Hypergraph projects

### ISSUE THREAD

**Issue by chartgerink** [dat-ecosystem-archive/project-updates#6]
Heyoo 👋

@dpaez, @juliangruber, and I are working on two projects utilizing the Dat ecosystem. We are funded and working quite a bunch on this, so we'd be excited to share our progress here :) Per the contributing doc, we post this issue first.

# p2pcommons (aka 🍐-to-🍐 commons) 
A set of specifications to make a peer-to-peer commons ([`@p2pcommons/specs`](https://github.com/p2pcommons/specs). These specifications define a class of  Dat archives, with specific metadata, resulting in what we call modules on the Dat network. These modules can either be of type content or user profile (i.e., we do not store content and profile in the same place, like for example Fritter did).

## SDK
We are building an SDK to implement these specifications and make application development easier ([`@p2pcommons/sdk-js`](https://github.com/p2pcommons/sdk-js). We also have a working group that develops the specifications further ([`@p2pcommons/working-group`](https://github.com/p2pcommons/working-group)).
This is aimed to be a base layer, for interoperable applications to be built on top of. One of those is Hypergraph.

# Hypergraph
An application utilizing the p2pcommons for project management, tracking, evaluation, planning, and sharing. We are currently primarily working on the CLI ([`@hypergraph-xyz/cli`](https://github.com/hypergraph-xyz/cli), but are starting our desktop development ([`@hypergraph-xyz/desktop`](https://github.com/hypergraph-xyz/desktop)).

# Funding
These projects are part of [Liberate Science](https://libscie.org), which is funded by the [Shuttleworth Foundation](https://shuttleworthfoundation.org) (this funding may run us until August 2022).

**Comment by cblgh** [comment]
@chartgerink :wave: i granted y'all write access!

(@RangerMauve lmk if you disagree, but i think it's pretty clear that p2pcommons should be in the repo :~)

**Comment by RangerMauve** [comment]
@cblgh Oh yeah! I totally agree. 😁

**Comment by RangerMauve** [comment]
@chartgerink Feel free to do a PR with your project info in a folder!

**Comment by chartgerink** [comment]
Yay 🎊 I will make the PR early next week :)
